version: '3.8'

services:
  # Cấu hình Database MySQL
  mysql:
    image: mysql:8.0
    container_name: msql-identity
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      # Thông tin từ appilication yaml
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: identity_service
    volumes:
      - mysql_data:/var/lib/mysql

  # Cấu hình Spring Boot App
  app:
    build: .
    container_name: identity-app
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      # Ghi đè url để springboot kết nối tới mysql container ở trên (tên service là 'mysql') thay vì 'localhost'
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/identity_service?useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    
volumes:
  mysql_data:
